name : gatsby deploy

on :
  push : 
    branches : [master]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Deploy
      uses: enriikke/gatsby-gh-pages-action@v2
      with:
        access-token: ${{ secrets.ACCESS_TOKEN }}
