name : gatsby deploy

on :
  push : 
    branches : [master]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps :
      - name: checkout code
        uses: actions/checkout@v2

      - name: packages install
        run: npm install

      - name: gatsby build
        run: gatsby build
        env:
          GH_API_KEY: ${{ secrets.ACCESS_TOKEN }}

      - name: deploy
        uses: maxheld83/ghpages@v0.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_PAT: ${{ secrets.ACCESS_TOKEN }}
          BUILD_DIR: 'public/'
     
